import type React from 'react';
import type { BackofficeReception, CatalogAgency, CatalogBrand, CatalogModel, CatalogTech, GuideItem, OperationCategory, ReceptionStep, SapTransferGroup } from '../types';

export type OperationContext = {
  receptionStep: ReceptionStep;
  setReceptionStep: React.Dispatch<React.SetStateAction<ReceptionStep>>;
  activeReception: BackofficeReception | null;
  setActiveReception: React.Dispatch<React.SetStateAction<BackofficeReception | null>>;
  accessoryPhotos: string[];
  setAccessoryPhotos: React.Dispatch<React.SetStateAction<string[]>>;
  scannedGuides: string[];
  setScannedGuides: React.Dispatch<React.SetStateAction<string[]>>;
  processedGuides: string[];
  setProcessedGuides: React.Dispatch<React.SetStateAction<string[]>>;
  inboxSearch: string;
  setInboxSearch: React.Dispatch<React.SetStateAction<string>>;
  classificationSearch: string;
  setClassificationSearch: React.Dispatch<React.SetStateAction<string>>;
  agencia: string;
  setAgencia: React.Dispatch<React.SetStateAction<string>>;
  selectedAgencyId: string;
  setSelectedAgencyId: React.Dispatch<React.SetStateAction<string>>;
  category: OperationCategory;
  setCategory: React.Dispatch<React.SetStateAction<OperationCategory>>;
  guideItems: GuideItem[];
  setGuideItems: React.Dispatch<React.SetStateAction<GuideItem[]>>;
  manifestPanelOpen: boolean;
  setManifestPanelOpen: React.Dispatch<React.SetStateAction<boolean>>;
  returnReason: string;
  setReturnReason: React.Dispatch<React.SetStateAction<string>>;
  returnTracking: string;
  setReturnTracking: React.Dispatch<React.SetStateAction<string>>;
  returnCourier: string;
  setReturnCourier: React.Dispatch<React.SetStateAction<string>>;
  sapTransferNumber: string;
  setSapTransferNumber: React.Dispatch<React.SetStateAction<string>>;
  sapGroups: SapTransferGroup[];
  setSapGroups: React.Dispatch<React.SetStateAction<SapTransferGroup[]>>;
  activeSapGroupId: string | null;
  setActiveSapGroupId: React.Dispatch<React.SetStateAction<string | null>>;
  newItem: { tipo: string; marca: string; modelo: string; cantidad: number };
  setNewItem: React.Dispatch<React.SetStateAction<{ tipo: string; marca: string; modelo: string; cantidad: number }>>;
  selectedItemIdx: number | null;
  setSelectedItemIdx: React.Dispatch<React.SetStateAction<number | null>>;
  itemSeriesInputs: Record<number, string>;
  setItemSeriesInputs: React.Dispatch<React.SetStateAction<Record<number, string>>>;
  pendingReceptions: BackofficeReception[];
  loading: boolean;
  inboxLoadError: string | null;
  isSubmitting: boolean;
  processingDateLabel: string;
  currentUserFullName: string;
  allReceptions: BackofficeReception[];
  historyLoading: boolean;
  CAC_AGENCIES: CatalogAgency[];
  MASTER_TECNOLOGIAS: CatalogTech[];
  MASTER_MARCAS: CatalogBrand[];
  MASTER_MODELOS: CatalogModel[];
  agencyDetails: CatalogAgency | undefined;
  availableBrandsConfig: CatalogBrand[];
  availableModels: CatalogModel[];
  isActiveSapDocumentFilled: boolean;
  sapDocumentConflict: string | null;
  startProcessingReception: (rec: BackofficeReception) => void;
  handlePrintConduce: (record: BackofficeReception) => void;
  fetchPending: (opts?: { silent?: boolean }) => Promise<void>;
  fetchHistory: (opts?: { silent?: boolean }) => Promise<void>;
  handleTestConnection: () => Promise<void>;
  initSapGroupsForConfig: () => void;
  handleUndoClassification: (guia: string) => Promise<void>;
  setShowAgencyModal: React.Dispatch<React.SetStateAction<boolean>>;
  addSapGroup: () => void;
  selectSapGroup: (groupId: string) => void;
  removeSapGroup: (groupId: string) => void;
  updateActiveSapDocument: (value: string) => void;
  addItem: () => void;
  completeCurrentGuides: () => Promise<void>;
  handleConfirmReturn: () => Promise<void>;
  compressImage: (file: File) => Promise<string>;
  setShowBulkModal: React.Dispatch<React.SetStateAction<boolean>>;
  setBulkTargetIdx: React.Dispatch<React.SetStateAction<number | null>>;
  onCompletedNextBox: () => void;
};
