export const SAP_TRANSFER_STATUS = {
  PENDIENTE_INGRESO_BODEGA: 'PENDIENTE_INGRESO_BODEGA',
  INGRESADO_BODEGA: 'INGRESADO_BODEGA',
  DEVUELTO_BLOQUE: 'DEVUELTO_BLOQUE',
} as const;

export type SapTransferStatus =
  (typeof SAP_TRANSFER_STATUS)[keyof typeof SAP_TRANSFER_STATUS];

export const BLOCK_RETURN_ELIGIBLE_STATUSES = [
  'RECEPCIONADO_BODEGA_GENERAL',
  'returned',
] as const;
